import {WildfireApiClient,type CommandOutcome,type ReadModel as ApiReadModel,type ReadModelPage} from "@wildfire-robotics/api-client/dist/index.js";
import type {CommandStage,CommandStatus,Context,DataState,OperatorSnapshot,ReadModel} from "./models";
import {QueryCache,adaptEnvelope,createQueryKey,type ReadEnvelope} from "./read-model";
type ReadKind="incidents"|"missions"|"fleetAssets"|"stations"|"deliveries"|"hazards"|"safetyOccurrences"|"recoveryCases";
interface ApiBoundary {list(kind:ReadKind,options:{deadline:Date;signal?:AbortSignal;limit?:number}):Promise<ReadModelPage>;commandOutcome(id:string,options:{deadline:Date;signal?:AbortSignal}):Promise<CommandOutcome>}
const reads:readonly [Context,ReadKind][]=[["incident","incidents"],["mission","missions"],["fleet","fleetAssets"],["station","stations"],["logistics","deliveries"],["hazard","hazards"],["safety","safetyOccurrences"],["recovery","recoveryCases"]];
const state=(value:ApiReadModel["freshness"]["state"]):DataState=>value==="fresh"?"current":value;
const stage=(value:CommandOutcome["state"]):CommandStage=>value==="acknowledged"?"acknowledged":value==="executed"?"executed":value==="verified"?"outcome-confirmed":value==="indeterminate"?"outcome-unknown":"accepted";
const summarize=(value:ApiReadModel["summary"]):string=>Object.entries(value).map(([key,item])=>`${key}: ${item===null?"unknown":String(item)}`).join(" · ")||"No summary fields returned.";
export class OperatorApiAdapter {
  readonly #api:ApiBoundary;private readonly tenant:string;private readonly region:string;
  private readonly incident:string;private readonly authorizationScope:string;
  private readonly cache=new QueryCache({maxReadRetries:2,jitter:()=>Math.floor(Math.random()*75)});
  constructor(options:{baseUrl:string;accessToken:()=>string|Promise<string>;tenant:string;region:string;incident?:string;authorizationScope?:string;api?:ApiBoundary}){this.#api=options.api??new WildfireApiClient({baseUrl:options.baseUrl,accessToken:options.accessToken});this.tenant=options.tenant;this.region=options.region;this.incident=options.incident??"active";this.authorizationScope=options.authorizationScope??"operator"}
  async readEnvelopes(signal?:AbortSignal):Promise<Readonly<Record<Context,ReadEnvelope<ReadModel>>>>{
    const deadline=new Date(Date.now()+10_000);
    const requests=reads.map(async([context,kind])=>{
      const key=createQueryKey({tenant:this.tenant,incident:this.incident,context,resource:kind,filters:{region:this.region},schemaVersion:"operator-v1",authorizationScope:this.authorizationScope});
      return this.cache.read(key,async cacheSignal=>{const linked=signal?AbortSignal.any([signal,cacheSignal]):cacheSignal;const page=await this.#api.list(kind,{deadline,limit:1,signal:linked});const model=mapRead(context,page.items[0])??unknownRead(context,"No authorized item returned");return adaptEnvelope({data:model,sourceTime:model.provenance.observedAt,receivedTime:model.provenance.receivedAt,asOfVersion:page.items[0]?.provenance.sourceVersion??null,state:model.state,provenance:[{source:model.provenance.source,lineage:model.provenance.lineage}],uncertainty:{description:model.uncertainty},limitations:model.limitation?[model.limitation]:[],simulated:false})});
    });
    const settled=await Promise.allSettled(requests);
    return Object.fromEntries(settled.map((result,index)=>{const context=reads[index]![0];if(result.status==="fulfilled")return [context,result.value];const reason=result.reason;return [context,adaptEnvelope({data:unknownRead(context,reason instanceof Error?reason.message:"Read unavailable"),sourceTime:null,receivedTime:new Date().toISOString(),asOfVersion:null,state:"unknown",provenance:[],limitations:["Context read failed; unaffected regions remain available."],simulated:false})]})) as Record<Context,ReadEnvelope<ReadModel>>;
  }
  async snapshot(signal?:AbortSignal,commandIds:readonly string[]=[]):Promise<OperatorSnapshot>{const deadline=new Date(Date.now()+10_000);const envelopes=await this.readEnvelopes(signal);const commandResults=await Promise.allSettled(commandIds.map(id=>this.#api.commandOutcome(id,{deadline,...(signal?{signal}:{})}).then(mapCommand)));const commands=commandResults.flatMap(result=>result.status==="fulfilled"?[result.value]:[]);return {tenant:this.tenant,region:this.region,generatedAt:new Date().toISOString(),models:reads.map(([context])=>envelopes[context].data).filter((item):item is ReadModel=>item!==null),commands}}
}
function mapRead(context:Context,item:ApiReadModel|undefined):ReadModel|undefined{if(!item)return undefined;const limitation=item.provenance.limitations?.join(" · ");return {context,title:`${context} — ${item.id}`,summary:summarize(item.summary),state:state(item.freshness.state),uncertainty:item.uncertainty.description,provenance:{source:`${item.provenance.producer}@${item.provenance.sourceVersion}`,observedAt:item.freshness.observedAt??item.freshness.recordedAt,receivedAt:item.freshness.recordedAt,lineage:item.provenance.digest},...(limitation?{limitation}:{})}}
function mapCommand(item:CommandOutcome):CommandStatus{return {id:item.commandId,stage:stage(item.state),detail:item.reason??`Gateway state: ${item.state}; authoritative: ${String(item.authoritative)}`,updatedAt:item.updatedAt}}
function unknownRead(context:Context,limitation:string):ReadModel{return {context,title:`${context} — unavailable`,summary:"No current authorized read model is available.",state:"unknown",uncertainty:"Unknown",provenance:{source:"Unavailable",observedAt:"Unknown",receivedAt:new Date().toISOString(),lineage:"None"},limitation}}
