import {WildfireApiClient,type CommandOutcome,type ReadModel as ApiReadModel,type ReadModelPage} from "@wildfire-robotics/api-client/dist/index.js";
import type {CommandStage,CommandStatus,Context,DataState,OperatorSnapshot,ReadModel} from "./models";
type ReadKind="incidents"|"missions"|"fleetAssets"|"stations"|"deliveries"|"hazards"|"safetyOccurrences"|"recoveryCases";
interface ApiBoundary {list(kind:ReadKind,options:{deadline:Date;signal?:AbortSignal;limit?:number}):Promise<ReadModelPage>;commandOutcome(id:string,options:{deadline:Date;signal?:AbortSignal}):Promise<CommandOutcome>}
const reads:readonly [Context,ReadKind][]=[["incident","incidents"],["mission","missions"],["fleet","fleetAssets"],["station","stations"],["logistics","deliveries"],["hazard","hazards"],["safety","safetyOccurrences"],["recovery","recoveryCases"]];
const state=(value:ApiReadModel["freshness"]["state"]):DataState=>value==="fresh"?"current":value;
const stage=(value:CommandOutcome["state"]):CommandStage=>value==="acknowledged"?"acknowledged":value==="executed"?"executed":value==="verified"?"outcome-confirmed":value==="indeterminate"?"outcome-unknown":"accepted";
const summarize=(value:ApiReadModel["summary"]):string=>Object.entries(value).map(([key,item])=>`${key}: ${item===null?"unknown":String(item)}`).join(" · ")||"No summary fields returned.";
export class OperatorApiAdapter {
  readonly #api:ApiBoundary;private readonly tenant:string;private readonly region:string;
  constructor(options:{baseUrl:string;accessToken:()=>string|Promise<string>;tenant:string;region:string;api?:ApiBoundary}){this.#api=options.api??new WildfireApiClient({baseUrl:options.baseUrl,accessToken:options.accessToken});this.tenant=options.tenant;this.region=options.region}
  async snapshot(signal?:AbortSignal,commandIds:readonly string[]=[]):Promise<OperatorSnapshot>{const deadline=new Date(Date.now()+10_000);const request=(context:Context,kind:ReadKind)=>this.#api.list(kind,{deadline,limit:1,...(signal?{signal}:{})}).then(page=>mapRead(context,page.items[0]));const models=(await Promise.all(reads.map(([context,kind])=>request(context,kind)))).filter((item):item is ReadModel=>item!==undefined);const commands=await Promise.all(commandIds.map(id=>this.#api.commandOutcome(id,{deadline,...(signal?{signal}:{})}).then(mapCommand)));return {tenant:this.tenant,region:this.region,generatedAt:new Date().toISOString(),models,commands}}
}
function mapRead(context:Context,item:ApiReadModel|undefined):ReadModel|undefined{if(!item)return undefined;const limitation=item.provenance.limitations?.join(" · ");return {context,title:`${context} — ${item.id}`,summary:summarize(item.summary),state:state(item.freshness.state),uncertainty:item.uncertainty.description,provenance:{source:`${item.provenance.producer}@${item.provenance.sourceVersion}`,observedAt:item.freshness.observedAt??item.freshness.recordedAt,receivedAt:item.freshness.recordedAt,lineage:item.provenance.digest},...(limitation?{limitation}:{})}}
function mapCommand(item:CommandOutcome):CommandStatus{return {id:item.commandId,stage:stage(item.state),detail:item.reason??`Gateway state: ${item.state}; authoritative: ${String(item.authoritative)}`,updatedAt:item.updatedAt}}
