import {contexts,type Context,type OperatorSnapshot} from "./models";

const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]??c));
export function renderOperatorShell(root:HTMLElement,snapshot:OperatorSnapshot):void {
  const model=(context:Context)=>snapshot.models.find(item=>item.context===context);
  root.innerHTML=`<header><p class="eyebrow">Tenant ${escape(snapshot.tenant)} · Region ${escape(snapshot.region)}</p><h1>Wildfire operations</h1><p>Generated <time datetime="${escape(snapshot.generatedAt)}">${escape(snapshot.generatedAt)}</time></p></header>
  <nav aria-label="Operational views"><div role="tablist" aria-label="Read model contexts">${contexts.map((c,i)=>`<button role="tab" id="tab-${c}" aria-controls="panel-${c}" aria-selected="${i===0}" tabindex="${i===0?0:-1}">${c}</button>`).join("")}</div></nav>
  <main id="workspace" tabindex="-1">${contexts.map((c,i)=>{const item=model(c);return `<section role="tabpanel" id="panel-${c}" aria-labelledby="tab-${c}" ${i===0?"":"hidden"}><h2>${escape(item?.title??c)}</h2>${item?`<p class="state state-${item.state}"><span class="sr-only">Data status: </span>${item.state}</p><p>${escape(item.summary)}</p><dl><div><dt>Uncertainty</dt><dd>${escape(item.uncertainty)}</dd></div><div><dt>Source</dt><dd>${escape(item.provenance.source)}</dd></div><div><dt>Observed</dt><dd><time datetime="${escape(item.provenance.observedAt)}">${escape(item.provenance.observedAt)}</time></dd></div><div><dt>Received</dt><dd><time datetime="${escape(item.provenance.receivedAt)}">${escape(item.provenance.receivedAt)}</time></dd></div><div><dt>Lineage</dt><dd><code>${escape(item.provenance.lineage)}</code></dd></div></dl>${item.limitation?`<aside aria-label="Data limitation">${escape(item.limitation)}</aside>`:""}`:`<p class="state state-unknown">unknown</p><p>No authorized read model was returned.</p>`}</section>`}).join("")}
  <section aria-labelledby="command-heading"><h2 id="command-heading">Command progress</h2><p>Acceptance, transport acknowledgement, execution, and physical outcome are separate facts.</p><ol class="commands">${snapshot.commands.map(c=>`<li><strong>${escape(c.stage)}</strong> — ${escape(c.detail)} <time datetime="${escape(c.updatedAt)}">${escape(c.updatedAt)}</time></li>`).join("")||"<li>Outcome unknown — no command status available.</li>"}</ol></section></main><div class="sr-only" role="status" aria-live="polite" id="announcer"></div>`;
  const tabs=[...root.querySelectorAll<HTMLButtonElement>('[role="tab"]')];
  const activate=(next:number,focus=true)=>{tabs.forEach((tab,i)=>{const selected=i===next;tab.setAttribute("aria-selected",String(selected));tab.tabIndex=selected?0:-1;const panel=root.querySelector<HTMLElement>(`#${tab.getAttribute("aria-controls")}`);if(panel)panel.hidden=!selected;});if(focus)tabs[next]?.focus();const live=root.querySelector("#announcer");if(live)live.textContent=`${tabs[next]?.textContent??"Unknown"} view selected`;};
  tabs.forEach((tab,index)=>{tab.addEventListener("click",()=>activate(index,false));tab.addEventListener("keydown",event=>{let next=index;if(event.key==="ArrowRight")next=(index+1)%tabs.length;else if(event.key==="ArrowLeft")next=(index-1+tabs.length)%tabs.length;else if(event.key==="Home")next=0;else if(event.key==="End")next=tabs.length-1;else return;event.preventDefault();activate(next);});});
}
