import {describe,it,expect} from "vitest";import axe from "axe-core";import {renderOperatorShell} from "../src/shell";import {contexts,type OperatorSnapshot} from "../src/models";
const snapshot:OperatorSnapshot={tenant:"tenant-a",region:"ca-bc",generatedAt:"2026-07-22T00:00:00Z",models:contexts.slice(0,7).map((context,index)=>({context,title:`${context} view`,summary:"Bounded operational summary",state:(index===1?"stale":index===2?"gap":index===3?"degraded":"current"),uncertainty:"95% interval ± 4",provenance:{source:"owning-context",observedAt:"2026-07-21T23:55:00Z",receivedAt:"2026-07-22T00:00:00Z",lineage:`digest-${context}`}})),commands:[{id:"c1",stage:"accepted",detail:"Policy accepted intent",updatedAt:"2026-07-22T00:00:00Z"},{id:"c1",stage:"outcome-unknown",detail:"Physical outcome not observed",updatedAt:"2026-07-22T00:01:00Z"}]};
function setup(){document.body.innerHTML='<div id="app"></div>';const root=document.querySelector<HTMLElement>("#app")!;renderOperatorShell(root,snapshot);return root}
describe("operator shell",()=>{
  it("has no detectable WCAG A/AA violations",async()=>{const root=setup();const result=await axe.run(root,{runOnly:{type:"tag",values:["wcag2a","wcag2aa"]},rules:{"color-contrast":{enabled:false}}});expect(result.violations).toEqual([])});
  it("exposes every context and explicit unknown/stale/gap/degraded states",()=>{const root=setup();expect(root.querySelectorAll('[role="tab"]')).toHaveLength(8);expect(root.textContent).toContain("unknown");expect(root.textContent).toContain("stale");expect(root.textContent).toContain("gap");expect(root.textContent).toContain("degraded")});
  it("supports arrow-key focus and selection",()=>{const root=setup();const tabs=[...root.querySelectorAll<HTMLButtonElement>('[role="tab"]')];tabs[0]!.focus();tabs[0]!.dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowRight",bubbles:true}));expect(document.activeElement).toBe(tabs[1]);expect(tabs[1]!.getAttribute("aria-selected")).toBe("true");expect(document.querySelector<HTMLElement>('#panel-mission')!.hidden).toBe(false)});
  it("distinguishes command lifecycle from physical outcome",()=>{const root=setup();expect(root.textContent).toContain("accepted");expect(root.textContent).toContain("outcome-unknown");expect(root.textContent).toContain("physical outcome")});
});
