//! Representation-independent contract conformance checks.

use prost::Message;
use serde::Serialize;
use serde_json::Value;
use sha2::{Digest, Sha256};
use std::{fs, path::Path};
use thiserror::Error;

/// Default maximum accepted internal envelope size (one mebibyte).
pub const DEFAULT_MAX_MESSAGE_BYTES: usize = 1_048_576;

/// Bounded decoder guarding allocation and parser work before Protobuf decode.
pub fn decode_bounded<M: Message + Default>(
    bytes: &[u8],
    max_bytes: usize,
) -> Result<M, ConformanceError> {
    if bytes.len() > max_bytes {
        return Err(ConformanceError::MessageTooLarge {
            actual: bytes.len(),
            maximum: max_bytes,
        });
    }
    M::decode(bytes).map_err(ConformanceError::Decode)
}

/// Encodes a message and refuses to produce an artifact exceeding its contract limit.
pub fn encode_bounded<M: Message>(
    message: &M,
    max_bytes: usize,
) -> Result<Vec<u8>, ConformanceError> {
    let encoded_len = message.encoded_len();
    if encoded_len > max_bytes {
        return Err(ConformanceError::MessageTooLarge {
            actual: encoded_len,
            maximum: max_bytes,
        });
    }
    Ok(message.encode_to_vec())
}

/// Serializes JSON with recursively sorted object keys for stable fixtures.
pub fn canonical_json<T: Serialize>(value: &T) -> Result<Vec<u8>, ConformanceError> {
    let mut value = serde_json::to_value(value)?;
    canonicalize_value(&mut value);
    let mut bytes = serde_json::to_vec_pretty(&value)?;
    bytes.push(b'\n');
    Ok(bytes)
}

fn canonicalize_value(value: &mut Value) {
    match value {
        Value::Array(values) => values.iter_mut().for_each(canonicalize_value),
        Value::Object(object) => {
            for child in object.values_mut() {
                canonicalize_value(child);
            }
            let mut entries: Vec<_> = std::mem::take(object).into_iter().collect();
            entries.sort_unstable_by(|left, right| left.0.cmp(&right.0));
            object.extend(entries);
        }
        _ => {}
    }
}

/// Verifies exact fixture bytes and returns their lowercase SHA-256 digest.
pub fn verify_golden(path: &Path, actual: &[u8]) -> Result<String, ConformanceError> {
    let expected = fs::read(path).map_err(|source| ConformanceError::ReadFixture {
        path: path.to_path_buf(),
        source,
    })?;
    if expected != actual {
        return Err(ConformanceError::GoldenMismatch(path.to_path_buf()));
    }
    Ok(format!("{:x}", Sha256::digest(actual)))
}

/// Stable failures produced by conformance checks.
#[derive(Debug, Error)]
pub enum ConformanceError {
    /// The encoded input exceeded its declared byte limit.
    #[error("message is {actual} bytes; maximum is {maximum}")]
    MessageTooLarge {
        /// Observed encoded byte length.
        actual: usize,
        /// Contract maximum encoded byte length.
        maximum: usize,
    },
    /// Protobuf decoding failed.
    #[error("invalid protobuf: {0}")]
    Decode(#[source] prost::DecodeError),
    /// Canonical JSON serialization failed.
    #[error("JSON serialization failed: {0}")]
    Json(#[from] serde_json::Error),
    /// A golden fixture could not be read.
    #[error("cannot read fixture {path}: {source}", path = path.display())]
    ReadFixture {
        /// Fixture path that could not be read.
        path: std::path::PathBuf,
        /// Underlying filesystem failure.
        source: std::io::Error,
    },
    /// Generated output differed from the reviewed golden fixture.
    #[error("generated bytes differ from golden fixture {path}", path = .0.display())]
    GoldenMismatch(std::path::PathBuf),
}
